### ISSUE TITLE
plex-media-server keeps crashing on gentoo-hardened

### ISSUE THREAD

**Issue by CMoH** [viddi87/gentoo-htpc#1]
I've been experiencing crashes with plex-media-server on my hardened server:

```
950877.477278] grsec: From 192.168.1.110: denied RWX mmap of <anonymous mapping> by /usr/lib64/plexmediaserver/Resources/Python/bin/python[python:24436] uid/euid:119/119 gid/egid:989/989, parent /usr/lib64/plexmediaserver/Plex Media Server[Plex Media Serv:24426] uid/euid:119/119 gid/egid:989/989
```

At the same time playback on clients gets interrupted.

Before moving to your overlay I was using this script here, which: https://github.com/drewbeer/overlay/blob/master/media-tv/plex-media-server/files/pax_fix.sh. Your ebuild seems to get a different approach on this, but is seems it is incomplete.

I am not sure which way is better, but maybe the link above helps.

**Comment by viddi87** [comment]
Does this happen when you do something specific or is it random?
I have been trying to reproduce this on a clean hardened build but everything seems to be fine so far.

**Comment by CMoH** [comment]
I've been using it for a while now, and it seems to have stopped crashing after changing my NIC. Maybe it's the normal failure path in the code that hits some denied caps on gentoo-hardened.

I'll reopen if it manifests again. Thank you for testing the problem - it made me consider that the spurious disconnects are the problem, and it seems changing the NIC is a good solution for now.
